### ISSUE TITLE
max CQ / sleep does not engage in MIX-mode

### ISSUE THREAD

**Issue by JEA3** [dg5lp/FT8-Helper-2.6.1#1]
Is it possible to have the cool down timer (max CQ / sleep) engage when using the new MIX-mode?

**Comment by dg5lp** [comment]
Sorry,  CQ/Sleep works only in pure CQ (Run) mode and only if not during Band-Hopping.

 

You can help yourself specifying two band hopping sequences for the same band:

- a MIX sequence

- and an S/P sequence with “Only wanted” without specifying any wanted calls or DXCC.

 

With the parameters “Max. Broken QSOs in CQ and S/P” you can set up how often the modes should be changed..

 

Band hopping and changing the strategy will hide full automatic working ;-)

 

 

Von: JEA3 ***@***.*** 
Gesendet: Montag, 5. Juni 2023 14:12
An: dg5lp/FT8-Helper-2.6.1
Cc: Subscribed
Betreff: [dg5lp/FT8-Helper-2.6.1] max CQ / sleep does not engage in MIX-mode (Issue #1)

 

Is it possible to have the cool down timer (max CQ / sleep) engage when using the new MIX-mode?
