### ISSUE TITLE
SP Mode not Functional 

### ISSUE THREAD

**Issue by kfallsbob** [dg5lp/FT8-Helper-2.6.1#2]
Running WSJT-X 2.6.1 

Helper Works on CQ but will not TX on SP. Just sits there and does nothing when activated.
Older versions of JT and HELPER worked like a dream.

Any suggestions???

**Comment by dg5lp** [comment]
Which strategy is selected ?

Any exclude filter used?

 

Von: kfallsbob ***@***.*** 
Gesendet: Sonntag, 1. Oktober 2023 23:52
An: dg5lp/FT8-Helper-2.6.1
Cc: Subscribed
Betreff: [dg5lp/FT8-Helper-2.6.1] SP Mode not Functional (Issue #2)

 

Running WSJT-X 2.6.1

Helper Works on CQ but will not TX on SP. Just sits there and does nothing when activated.
Older versions of JT and HELPER worked like a dream.

Any suggestions???
