### ISSUE TITLE
source code?

### ISSUE THREAD

**Issue by PalinuroSec** [dg5lp/FT8-Helper-2.6.1#3]
hello, is the source code publicly available? i would like to work on a linux port, but the software seems closed source

**Comment by dg5lp** [comment]
The software is free for non commercial use, but the code is not open source.  I have no support team and I do not want receive error reports from forked versions. The source code was written in a macro language used by the commercial sowftare QuckMacros.  There is no compatibel version of QuckMacros for Linux.
